language: node_js
node_js:
  - '6'
sudo: false
addons:
  sauce_connect:
    no_ssl_bump_domains: all
  jwt:
    secure: bhnTF5CMolgrF9sYGNij8yeBDJWEEtJ9MKq7bJ8Nh9AbiaoJ0Nyxx3XRVMz6ktA7LKSkz7j50DcM95nQaa/OaHCYt9x+0hitPRMWgDf3UdAJdAAr3mwbxk9uLXpztUWVxzyrhLP5qXPgelMqowuQUuiAGDJ8/XpXGSEoPFVZrYs=
before_install:
  - npm install -g bower
  - bower install
  - npm install -g npm@'>=3.0.0'
script: travis_wait gulp test:saucelabs
