language: node_js
node_js:
  - '6'
sudo: false
addons:
  sauce_connect:
    no_ssl_bump_domains: all
  jwt:
    secure: suDsLYkGp2tfX+PhjOPBja33Ms9ZhyT6tMayWGqq9wL4ymmRe7Cy/8Cx0u669umfZ15ctalKyOy/NfeYK83/skTTbTrGzemp8xCXeOO0fh3ZkTCN1dGDvS999M+rsHPvULQuuY80GK8azmgF2X9+9UKPibMzHKAk9fjNsukhZUID0e55xq72i4ZUiEp6q0WPf6Aw5FPaS3rRaDmzPKl4644pxC7/VxX+ksHN+Fm1k5sKiJRaJf9hJpiSWJA8kn1HTR3ge3tcJxuNjJakSvCyWg0b0/W/1Ax3i1Jf/Mmf3ng7IMm83MdS9zqxka/jUZYPzMiIufriEEiNWI+d8+4QTij3yBxztazhduSP10blhgjKqYv7isj8ecWom4M2O5pB0t7wkQ9gjU/7yEMVlN9ZjjOH4qMYt6UdprG+Vsa7URqtQHJuZgACV5Bzqi0D/XZ6KzO/v5hmLIgfzsqfvshUxerOFzz6ADTQtEHZuB49jDsn2VsYNAkd8d/OHTrGj9BGSFdBGZu0b1OE6diqODThG0qFRJ3KJ3XltJktg0InqIx4yzms7F9A58n94KRvMUjK33naDWKjDJlTq2ogg2cX7b2MpCw0HktQADoVtct0AKbVpC9Ew5PHqmt+8X4WMfYGgYnkUo5ZwJ4Jdq/9xMLjPBhnN2/TWWQdtuZPRf6QXk0=
before_install:
  - npm install -g bower
  - bower install
  - npm install -g npm@'>=3.0.0'
script: travis_wait gulp test:saucelabs
