language: node_js
node_js:
  - '6'
sudo: false
addons:
  sauce_connect:
    no_ssl_bump_domains: all
  jwt:
    secure: W3HPVyE0nDpPIu5goFk5hfhQHSQIARtyUP1qNa7r+ontTMygo6a1ZsglLhTvrAscaHGL8PBw2LTUlcivDeGs+HFfk9+Lqiica/bn31kX3z5/bDD3nugHc8vUDfOfoV6aWW0C2y5gVqXUEPVoOvzKRgxZLoTH3UsppTVFs8EIGXY=
before_install:
  - npm install -g bower
  - bower install
  - npm install -g npm@'>=3.0.0'
script: travis_wait gulp test:saucelabs
