language: node_js
node_js:
  - '6'
sudo: false
addons:
  sauce_connect:
    no_ssl_bump_domains: all
  jwt:
    secure: r4mk22xEQZH/Z71B4BniLL1Us9Oq8zj09lo8QA1Tj9osCMNMQdS2xsRSwhMv/7ZtJfpL94HT13pfyRWXx66F3nk+cbOmt7obG3Sq6KlnwJUHFMWqTmooIxZN9WA/27RztRXqLEm8fAaquoESrZcUiSCMm13GZBgo+ZbbXErSb7FF316WA+EwkFH8L+kuWbibOcfA+AMLHVf9ZKeaqFID1Hh4SLsNQk8Ij7wX0oMppyblbKnQs8zIWlmdAE7kB48ro31xcPAUZXttRtlrK2MzHmHw68EkffIB9C3Bx7sLjHy2r9I/l/u7Q6qSQsLVZbICy+zOFHYRqm8OOOCiMKCQWDxLTFMT+Wx2X13CA+zVFsjMGxc2nPXTg4Y8GSaIxeZPUd3WWwQfBjxLkCdyJOeqWoI535D6ZP2Wf+yfHLloe3AEysE6Gz+HxUUGS4vvkOUcRmyHkvE7OW7ZmowYcKNZKdS9RIBWH1dGOOjbwbB68AdL/5zOw/U3vTVJSMvilEZMa2fGyiHtJ/TaTdwMyffpwCh8aWehXnRw8Q0HYOC2CAwfVMTAFBesNgUvhsFb1s7/iIOty1JGeA1N/QzztxbZ2Ch7VpEbZFmdAULcq2Xg3fdeSNNYUoGrjT7Yk1MVssZ/Jn4ugCdSpUAVdB7gIuHGiIDIeZn4T7DhdNwpTw85VIA=
before_install:
  - npm install -g bower
  - bower install
  - npm install -g npm@'>=3.0.0'
script: travis_wait gulp test:saucelabs
